from dotenv import load_dotenv
import os

load_dotenv()

print("✅ Testing .env loading...")
print("OPENAI_API_KEY:", os.getenv("OPENAI_API_KEY"))
patterns = tool_keywords = {
    "nmap": ["PORT", "STATE", "SERVICE"],
    "gobuster": ["Status", "Size", "URL"],
    "ffuf": ["Status:", "Title:"],
    "dirb": ["---- Scanning URL", "==> Directory Listing"],
    "dirbuster": ["Found", "dirs"],
    "sqlmap": ["sqlmap", "testing connection", "parameter"],
    "nikto": ["Nikto", "OSVDB"],
    "wpscan": ["WordPress", "wp-content"],
    "whatweb": ["WhatWeb", "Identified"],
    "amass": ["Discovered", "subdomains"],
    "sublist3r": ["[-]", "Found"],
    "assetfinder": ["http"],
    "httprobe": ["https://", "http://"],
    "waybackurls": ["web.archive.org"],
    "jsfinder": ["Found JS:", "URL:"],
    "theHarvester": ["[-]", "emails", "hosts"],
    "dnsrecon": ["Name", "Type", "Target"],
    "dnsenum": ["dnsenum", "records"],
    "dig": ["ANSWER SECTION", "IN"],
    "masscan": ["open tcp", "Discovered open port"],
    "zmap": ["Starting ZMap", "Results"],
    "enum4linux": ["Enumerating", "Shares", "RID"],
    "nbtscan": ["NetBIOS", "Name"],
    "smbclient": ["smb", "NT_STATUS"],
    "rpcclient": ["rpcclient", "EnumDomUsers"],
    "crackmapexec": ["CME", "WIN", "SUCCESS"],
    "responder": ["NBTNS", "poisoned"],
    "mitm6": ["Listening", "IPv6", "spoof"],
    "bettercap": ["net.probe", "discovery"],
    "aircrack-ng": ["WEP", "WPA", "IVs"],
    "reaver": ["WPS", "PIN"],
    "bully": ["BSSID", "ESSID", "WPS"],
    "kismet": ["SSID", "Channel", "BSSID"],
    "wireshark": ["Frame", "Ethernet", "IP"],
    "tcpdump": ["IP", "Flags", "length"],
    "hydra": ["[DATA]", "[ATTEMPT]"],
    "medusa": ["ACCOUNT FOUND", "host"],
    "john": ["Loaded", "password hashes"],
    "hashcat": ["Session", "Status", "Recovered"],
    "hash-identifier": ["Possible Hashs"],
    "cewl": ["Generated", "wordlist"],
    "crunch": ["Generating", "wordlist"],
    "burpsuite": ["Intercept", "GET", "POST"],
    "zap": ["ZAP", "Alerts", "Spider"],
    "metasploit": ["msf", "exploit", "session"],
    "msfvenom": ["Payload", "Options"],
    "exploitdb": ["EDB-ID", "Title:"],
    "searchsploit": ["Exploit Title", "EDB-ID"],
    "autopsy": ["Autopsy", "case"],
    "volatility": ["Volatility", "Processes"],
    "strings": ["ASCII", "Unicode"],
    "binwalk": ["DECIMAL", "DESCRIPTION"],
    "exiftool": ["ExifTool Version Number"],
    "gdb": ["gdb", "breakpoint"],
    "radare2": ["[0x", "r2"],
    "ghidra": ["Analyzing", "Decompiled"],
    "strace": ["execve(", "read("],
    "ltrace": ["__libc_start_main", "malloc"],
    "netstat": ["tcp", "udp", "LISTEN"],
    "ss": ["State", "Recv-Q"],
    "lsof": ["COMMAND", "PID", "USER"],
    "ps": ["PID", "TTY", "STAT"],
    "whoami": ["root", "admin"],
    "id": ["uid=", "gid="],
    "uname": ["Linux", "Darwin", "x86_64"],
    "ls": ["Desktop", "Downloads", "Documents"],
    "cat": ["/etc/passwd", "root:"],
    "grep": ["root", "password", "flag"],
    "nc": ["listening", "connection"],
    "socat": ["forwarding", "stream"],
    "ssh": ["login", "key", "password"],
    "scp": ["Transferred", "Permission"],
    "rsync": ["bytes", "copied"],
    "ftp": ["Connected", "Login successful"],
    "tftp": ["Transfer successful"],
    "telnet": ["Connected", "Escape character"],
    "curl": ["HTTP", "200 OK"],
    "wget": ["Saving to", "HTTP request sent"],
    "curl": ["HTTP/1.1", "200 OK"],
    "openssl": ["Certificate", "key"],
    "gobuster": ["Found", "Status"],
    "ffuf": [":: Progress", "Status"],
    "wfuzz": ["Payload", "Total requests"],
    "nuclei": ["[INF]", "[VULN]"],
    "nikto": ["+ OSVDB", "Server:"],
    "openvas": ["Report", "Vulnerability"],
    "nessus": ["Plugin", "Severity"],
    "burp scanner": ["Issue:", "Severity:"],
    "sn1per": ["Recon", "Status"],
    "netdiscover": ["IP", "MAC Address"],
    "arp-scan": ["Interface", "MAC"],
    "ettercap": ["MITM", "Sniffed"],
    "dsniff": ["Passwords", "Captured"],
    "tcpflow": ["flow", "connection"],
    "xhydra": ["login", "target"],
    "cain and abel": ["Password", "Hash"],
    "recon-ng": ["[recon-ng]", "Domain"],
    "sherlock": ["Username", "Found on"],
    "instaloader": ["Downloading", "Profile"],
    "maltego": ["Entities", "Graph"],
    "sankey": ["flow", "connection"],
    "cyberchef": ["Recipe", "Input"],
    "bloodhound": ["Query", "Graph"],
    "neo4j": ["MATCH", "RETURN"],
    "empire": ["listener", "agent"],
    "sliver": ["implant", "session"],
    "linpeas": ["Possible", "Enumeration"],
    "winpeas": ["Checking", "Finding"],
    "pspy": ["Process", "Running"],
    "gtfobins": ["suid", "capabilities"],
    "payloadsallthethings": ["payload", "bypass"],
    "seclists": ["Common", "Passwords"],
    "rockyou": ["123456", "password"],
    "crackstation": ["dehashed", "plaintext"]
}